### ISSUE TITLE
Drop unsupported versions

### ISSUE THREAD

**Issue by garak** [peter279k/fork-CalendR#5]
I think the following should be dropped, being out of support:

* PHP < 7.3 see https://www.php.net/supported-versions.php
* Symfony < 4.4 see https://symfony.com/releases

Moreover, support for Symfony 5 should be added

**Comment by peter279k** [comment]
Hi @garak, thanks for your reporting issue. And I create related PR.

Please review that and suggest some recommendations on that :).

**Comment by peter279k** [comment]
It's released: https://github.com/peter279k/fork-CalendR/releases/tag/3.1.0
